
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

